config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :admin do
    resources :users do
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'

      collection do
        get 'freeze_users'
      end
      member do
        patch 'add_freeze'
        delete 'remove_freeze'
      end
    end

    resources :posts

    get 'search' => 'posts#search'
  end

  scope module: :public do

    root to: 'homes#top'

    devise_scope :user do
      post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    end

    get 'relationships/followers'
    get 'relationships/followings'

    resources :users do
      resource :relationships, only: [:create, :destroy]

      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'

      member do   #member doを使うと、ユーザーidが含まれてるurlを使えるようになる（users/:id/favorites）
        get :favorites
        patch 'release'
        patch 'nonrelease'
      end

    end
      get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
      patch '/users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'

    resources :posts do
      resource :favorites, only: [:create, :destroy]  #いいねのidはURLに含める必要がない(params[:id]を使わなくても良い)ため、resourceを使う。URLに/:idを含めない形
      resources :post_comments, only: [:create, :destroy]
      get 'search' => 'posts#search'
    end

  end

end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image

  validates :image, presence: true

  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def self.search(word)
    where(["introduction LIKE?","%#{word}%"])
  end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :admin_scan
  def show
    @post = Post.find(params[:id])
  end

  def search
    @range = params[:range]
    @order = params[:order]
    @user = params[:user_id]
    if @range == 'ユーザ'
      @users = User.search(params[:word])

    elsif @range == '投稿' && @order == '人気順'
      @posts = Post.search(params[:word])
                   .includes(:favorited_users).sort {|a,b| b.favorited_users.size <=> a.favorited_users.size}

    elsif @range == '投稿' && @order == '新着順'
      @posts = Post.search(params[:word])
                   .order(created_at: :desc)

    else
      @posts = Post.search(params[:word])
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to admin_search_path
  end

  def post_params
    params.require(:post).permit(:image, :introduction, :user_id)
  end

end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/_list.html.erb
<div class="row p-2">
    <% posts.each do |post| %>
      <% if post.image.attached? %>
        <div class="col-4">
          <div class="row p-1">
                <%= link_to admin_post_path(post.id) do %>
                <%= image_tag post.image, size: "300x200" %>
                <% end %>
          </div>

          <div class="row p-1">
            <div>
              <%= link_to admin_user_path(post.user) do %>
              <%= image_tag post.user.get_profile_image(70,70), size: "70x70", class: "rounded-circle" %>
              <% end %>
            </div>

            <div class="col-8 offset-1">
              <div class="row">
                <%= post.introduction %>
              </div>
              <div class="row">
                <div style="color :gray"><%= post.user.name %></div>
              </div>
              <div class="row">
                <div style="color :gray"><%= post.created_at.strftime('%Y/%m/%d') %></div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

app/views/admin/posts/search.html.erb
<%= form_with url: admin_search_path, local: true, method: :get do |f| %>
  <table>
    <div class="row py-4 justify-content-center">
      <div class="col-4">
        <%= f.text_field :word, placeholder: '検索ワードを入力', size: "40x10", value: params[:word] %>
      </div>
      <div class="col-1">
        <%= f.select :range, options_for_select([['ユーザ'], ['投稿']], @range) %>
      </div>
      <div class="col-1">
        <% if @range == '投稿' %>
          <%= f.select :order, options_for_select([['新着順'], ['人気順']], @order) %>
        <% end %>
      </div>
      <div class="col-1">
        <%= f.submit "検索", class: "btn btn-primary" %>
      </div>
    </div>
  </table>
<% end %>

<table>
  <% if @range == 'ユーザ' %>
    <% if @users.exists? %>
      <% @users.each do |user| %>
        <div class="row p-2 d-flex justify-content-center">
          <div class="col-1">
            <%= link_to admin_user_path(user.id) do %>
            <%= image_tag user.get_profile_image(70,70), size: "70x70", class: "rounded-circle" %>
            <% end %>
          </div>
          <div class="col-4">
            <div><strong><%= user.name %></strong></div>
            <div><%= user.introduction %></div>
          </div>
        </div>
        <hr>
      <% end %>
    <% else %>
      <p>ユーザが見つかりませんでした。</p>
    <% end %>

  <% elsif @range == '投稿' && @order == '人気順' %>
    <%= render 'list', posts: @posts, user: @user %>

  <% elsif @range == '投稿' && @order == '新着順' %>
    <%= render 'list', posts: @posts, user: @user %>

  <% else %>
    <% if @posts.exists? %>
      <%= render 'list', posts: @posts, user: @user %>
    <% else %>
      <p>投稿が見つかりませんでした。</p>
    <% end %>

  <% end %>
</table>

app/views/admin/posts/show.html.erb
<div class="row pt-5 pl-5">
  <div class="col-1">
    <%= link_to admin_user_path(@post.user) do %>
    <%= image_tag @post.user.get_profile_image(70,70), size: "70x70", class: "rounded-circle" %>
    <% end %>
  </div>
  <div class="col-8 d-flex align-items-center">
    <strong><%= @post.user.name %></strong>
  </div>
  <div class="col-2">
    <%= link_to "投稿を削除する", admin_post_path(@post.id), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-danger" %>
  </div>
</div>

<div class="row pt-3">
  <div class="col-4 offset-2">
    <div style="color :gray"><%= @post.created_at.strftime('%Y/%m/%d') %></div>
  </div>
</div>
<div class="row">
  <div class="col-4 offset-2">
    <%= @post.introduction %>
  </div>
</div>

<div class="row pt-3">
  <div class="col-5 offset-2">
    <%= image_tag @post.image, size: "450x300" %>
  </div>
</div>

<div class="row pt-1">
  <div class="col-4">
    <% @post.post_comments.each do |post_comment| %>
      <table>
        <td class="d-flex align-items-start">
          <%= link_to admin_user_path(post_comment.user) do %>
          <%= image_tag post_comment.user.get_profile_image(30,30) %>
          <% end %>
        </td>
        <td>
          <strong><%= post_comment.user.name %></strong> <%= post_comment.comment %><br>
          <div style="color :gray"><%= post_comment.created_at.strftime('%Y/%m/%d') %>
            <%= link_to "削除", post_post_comment_path(post_comment.post, post_comment), method: :delete %>
          </div>
        </td>
      </table>
    <% end %>
  </div>
</div>