config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :admin do
    resources :users do
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'

      collection do
        get 'freeze_users'
      end
      member do
        patch 'add_freeze'
        delete 'remove_freeze'
      end
    end

    resources :posts

    get 'search' => 'posts#search'
  end

  scope module: :public do

    root to: 'homes#top'

    devise_scope :user do
      post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    end

    get 'relationships/followers'
    get 'relationships/followings'

    resources :users do
      resource :relationships, only: [:create, :destroy]

      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'

      member do   #member doを使うと、ユーザーidが含まれてるurlを使えるようになる（users/:id/favorites）
        get :favorites
        patch 'release'
        patch 'nonrelease'
      end

    end
      get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
      patch '/users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'

    resources :posts do
      resource :favorites, only: [:create, :destroy]  #いいねのidはURLに含める必要がない(params[:id]を使わなくても良い)ため、resourceを使う。URLに/:idを含めない形
      resources :post_comments, only: [:create, :destroy]
      get 'search' => 'posts#search'
    end

  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # is_deletedがfalseならtrueを返すようにしている
  def active_for_authentication?
    super && (is_deleted == false)
  end

  enum status:{nonreleased: 0, released: 1}

  scope :freezed, -> { where(is_freeze: true) }
  scope :not_freezed, -> { where(is_freeze: false) }

  has_one_attached :profile_image
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'no_-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  validates :name, presence: true
  validates :email, presence: true

  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_posts, through: :favorites, source: :post
  has_one :freeze, dependent: :destroy

  # フォローをした、されたの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  #わかりやすくするためにreverse_of_relationshipsという名前にしている
  #class_name: "Relationship"でRelationshipテーブルを参照、foreign_key(外部キー)で参照するカラムを指定

  # follow一覧画面で使う
  has_many :followings, through: :relationships, source: :followed              #relationshipsテーブルからfollowd_idのデータを参照
  has_many :followers, through: :reverse_of_relationships, source: :follower    #reverse_of_relationshipsテーブルからfollower_idのデータを参照
  #throughでスルーするテーブル、sourceで参照するカラムを指定

  # フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定
  def following?(user)
    followings.include?(user)
  end

  def self.guest
    find_or_create_by!(name: 'ゲストユーザー', email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      # user.confirmed_at = Time.now  # Confirmable を使用している場合は必要
      # 例えば name を入力必須としているならば， user.name = "ゲスト" なども必要
    end
  end

  def self.search(word)
      where(["name LIKE?","%#{word}%"])
  end

end

app/models/user/freeze.rb
class User::Freeze < ApplicationRecord
  belongs_to :user
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :admin_scan
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.all
  end

  def freeze_users
    @users = User.freezed
  end

  def add_freeze
    @user = User.find(params[:id])
    @user.update(is_freeze: true) if @user.is_freeze == false
    redirect_to request.referer
  end

  def remove_freeze
    @user = User.find(params[:id])
    @user.update(is_freeze: false) if @user.is_freeze == true
    redirect_to request.referer
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_users.html.erb
<% users.each do |user| %>
  <div class="row p-2 d-flex justify-content-center">
    <div class="col-1">
      <%= link_to admin_user_path(user.id) do %>
        <%= image_tag user.get_profile_image(70,70), size: "70x70", class: "rounded-circle" %>
      <% end %>
    </div>
    <div class="col-4">
      <div><strong><%= user.name %></strong></div>
      <div><%= user.introduction %></div>
    </div>
    <div class="col-2 offset-1 d-flex align-items-center">
      <% if user.is_freeze? %>
        <%= button_to '停止解除', remove_freeze_admin_user_path(user), method: :delete, class: "btn btn-outline-success" %>
      <% else %>
        <%= button_to 'アカウント停止', add_freeze_admin_user_path(user), method: :patch, "data-confirm" => "本当に停止しますか？", class: "btn btn-outline-danger" %>
      <% end %>
    </div>
  </div>
  <hr>
<% end %>

app/views/admin/users/freeze_users.html.erb
<%= render 'admin/users/users', users: @users %>

app/views/admin/users/index.html.erb
<div class="row p-3">
  <%= link_to "フリーズ一覧", freeze_users_admin_users_path, class: "btn btn-outline-primary" %>
</div>
<%= render 'admin/users/users', users: @users %>

app/views/admin/users/show.html.erb
<div class="row pt-5">
  <div class="col-1"><%= image_tag @user.get_profile_image(70,70), size: "70x70", class: "rounded-circle" %></div>
  <div class="col-2 d-flex align-items-center"><strong><%= @user.name %></strong></div>

  <div class="col-2">
    <%= @user.followings.count %></br>
    <%= link_to "フォロー中", admin_user_followings_path(@user.id) %>
  </div>
  <div class="col-2">
    <%= @user.followers.count %></br>
    <%= link_to "フォロワー", admin_user_followers_path(@user.id) %>
  </div>
  <div class="col-2 offset-1 d-flex align-items-center">
    <% if @user.is_freeze? %>
      <%= button_to '停止解除', remove_freeze_admin_user_path(@user), method: :delete, class: "btn btn-outline-success" %>
    <% else %>
      <%= button_to 'アカウント停止', add_freeze_admin_user_path(@user), method: :patch, "data-confirm" => "本当に停止しますか？", class: "btn btn-outline-danger" %>
    <% end %>
  </div>
</div>

  <div class="row pt-2">
    <div class="col-6 offset-1">
      <%= @user.introduction %>
    </div>
  </div>

  <hr>

  <div class="row pt-3">
    <% @posts.each do |post| %>
      <% if post.image.attached? %>
        <div class="col-3 pb-2">
          <%= link_to admin_post_path(post.id) do %>
          <%= image_tag post.image, size: "270x250" %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>