config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :admin do
    resources :users do
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'

      collection do
        get 'freeze_users'
      end
      member do
        patch 'add_freeze'
        delete 'remove_freeze'
      end
    end

    resources :posts

    get 'search' => 'posts#search'
  end

  scope module: :public do

    root to: 'homes#top'

    devise_scope :user do
      post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    end

    get 'relationships/followers'
    get 'relationships/followings'

    resources :users do
      resource :relationships, only: [:create, :destroy]

      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'

      member do   #member doを使うと、ユーザーidが含まれてるurlを使えるようになる（users/:id/favorites）
        get :favorites
        patch 'release'
        patch 'nonrelease'
      end

    end
      get '/users/:id/unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
      patch '/users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'

    resources :posts do
      resource :favorites, only: [:create, :destroy]  #いいねのidはURLに含める必要がない(params[:id]を使わなくても良い)ため、resourceを使う。URLに/:idを含めない形
      resources :post_comments, only: [:create, :destroy]
      get 'search' => 'posts#search'
    end

  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>NekoNoShukaisho</title>

    <script src="https://kit.fontawesome.com/1fc108571b.js" crossorigin="anonymous"></script>
     <meta charset="UTF-8"　/>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  
  </head>

  <body>
    <div class="image">
    <div id="header" class="fixed-top border-bottom" style="height:80px; background-color: #ffffff;">
      <div class="container">
        <div class="row pt-2 d-flex align-items-center">

          <div class="col-1">
            <%= image_tag "neko.jpg", size: "90x60" %>
          </div>
          <% if admin_signed_in? %>

            <div class="col-2 offset-8">
              <%= link_to destroy_admin_session_path,method: :delete, class: "nav-link active" do %>
                <button type="button" class="btn btn-outline-secondary">ログアウト</button>
              <% end %>
            </div>

          <% elsif user_signed_in? %>
            <div class="col-4">
              ＜<%= current_user.name %>さんいらっしゃい！
            </div>

            <div class="col-1">
              <%= link_to "＋", new_post_path, class: "btn btn-outline-secondary rounded-circle btn-lg" %>
            </div>

            <div class="col-4 d-flex justify-content-end">
              <div style="color :gray"><%= current_user.email %></div>
            </div>

            <div class="col-2">
              <%= link_to destroy_user_session_path, method: :delete, class: "nav-link active" do %>
                <button type="button" class="btn btn-outline-secondary">ログアウト</button>
              <% end %>
            </div>

          <% else %>

          <% end %>

        </div>
      </div>
    </div>
    </div>

    <div style="padding-top:80px; padding-bottom:80px; height:100%">
      <div class="container">
        <%= yield %>
      </div>
    </div>


    <div id="footer" class="fixed-bottom border-top" style="height:80px; background-color: #ffffff;">
      <div class="container">
        <div class="row p-3 d-flex justify-content-center">
          <% if user_signed_in? %>
                  <div class="col-1">
                    <%= link_to posts_path, class: "nav-link border-dark active btn btn-outline-light rounded-circle btn-lg" do %>
                      <i class="fa-solid fa-house-chimney"></i>
                    <% end %>
                  </div>

                  <div class="col-1">
                    <%= link_to post_search_path(current_user), class: "nav-link border-dark active btn btn-outline-light rounded-circle btn-lg" do %>
                      <i class="fa-solid fa-magnifying-glass"></i>
                    <% end %>
                  </div>

                  <div class="col-1">
                    <%= link_to favorites_user_path(current_user), class: "nav-link border-dark active btn btn-outline-light rounded-circle btn-lg" do %>
                      <i class="fa-solid fa-heart"></i>
                    <% end %>
                  </div>

                  <div class="col-1">
                    <%= link_to user_path(current_user), class: "nav-link border-dark active btn btn-outline-light rounded-circle btn-lg" do %>
                      <i class="fa-solid fa-user"></i>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>

          <% elsif admin_signed_in? %>

          <div class="col-1">
            <%= link_to admin_search_path(current_user), class: "nav-link border-dark active btn btn-outline-light rounded-circle btn-lg" do %>
              <i class="fa-solid fa-magnifying-glass"></i>
            <% end %>
          </div>

          <div class="col-1">
            <%= link_to admin_users_path, class: "nav-link border-dark active btn btn-outline-light rounded-circle btn-lg" do %>
              <i class="fa-solid fa-user"></i>
            <% end %>
          </div>
          <% else %>
          <% end %>
        </div>
      </div>
    </div>
  </body>
</html>